import json
import random

# Definir la lista de datos con todos los registros y campos adicionales
data_full = [
    
        {"name": "Alan David Balbuena Zavala",
            "email": "221229@ids.upchiapas.edu.mx", "matricula": "221229"},
        {"name": "Alan Emmanuel Diaz Coutiño",
            "email": "221191@ids.upchiapas.edu.mx", "matricula": "221191"},
        {"name": "Andres Guizar Gomez",
            "email": "213360@ids.upchiapas.edu.mx", "matricula": "213360"},
        {"name": "Ángel Manuel Bautista Vázquez",
            "email": "213347@ids.upchiapas.edu.mx", "matricula": "213347"},
        {"name": "Antonio Francisco Martinez Simuta",
            "email": "203405@ids.upchiapas.edu.mx", "matricula": "203405"},
        {"name": "Carlos Eduardo Chanona Aquino",
            "email": "221233@ids.upchiapas.edu.mx", "matricula": "221233"},
        {"name": "Carlos Eduardo Gumeta Navarro",
            "email": "221199@ids.upchiapas.edu.mx", "matricula": "221199"},
        {"name": "Carlos Enrique Barriga Aguilar",
            "email": "221188@ids.upchiapas.edu.mx", "matricula": "221188"},
        {"name": "Carlos Esteban Rivera Perez",
            "email": "213530@ids.upchiapas.edu.mx", "matricula": "213530"},
        {"name": "Carlos Ivan Cruz Zarmiento",
            "email": "221236@ids.upchiapas.edu.mx", "matricula": "221236"},
        {"name": "Carlos Raúl Lievano Ovando",
            "email": "221202@ids.upchiapas.edu.mx", "matricula": "221202"},
        {"name": "Cesar Gómez Aguilera",
            "email": "213507@ids.upchiapas.edu.mx", "matricula": "213507"},
        {"name": "Cristian Gerardo Vázquez Ramos",
            "email": "221267@ids.upchiapas.edu.mx", "matricula": "221267"},
        {"name": "Cristian Ovando Gómez",
            "email": "221256@ids.upchiapas.edu.mx", "matricula": "221256"},
        {"name": "Darinel Escobar",
            "email": "221192@ids.upchiapas.edu.mx", "matricula": "221192"},
        {"name": "Darío Antonio Gutiérrez Álvarez",
            "email": "221245@ids.upchiapas.edu.mx", "matricula": "221245"},
        {"name": "David Antonio Gómez González",
            "email": "221197@ids.upchiapas.edu.mx", "matricula": "221197"},
        {"name": "Diego Antonio Ortiz Cruz",
            "email": "221277@ids.upchiapas.edu.mx", "matricula": "221277"},
        {"name": "Diego Carmona Bernal",
            "email": "213498@ids.upchiapas.edu.mx", "matricula": "213498"},
        {"name": "Edrei Alvarez Hernandez",
            "email": "203140@ids.upchiapas.edu.mx", "matricula": "203140"},
        {"name": "Esmirna Jacqueline PEREZ SUCHIAPA",
            "email": "eperez@ids.upchiapas.edu.mx", "matricula": ""},
        {"name": "Francisco De Jesús Escobar Gutiérrez",
            "email": "221193@ids.upchiapas.edu.mx", "matricula": "221193"},
        {"name": "Francisco Emmanuel Estrada Rodríguez",
            "email": "213671@ids.upchiapas.edu.mx", "matricula": "213671"},
        {"name": "Gerardo Jafet Toledo Cañaveral",
            "email": "211228@ids.upchiapas.edu.mx", "matricula": "211228"},
        {"name": "Héctor Uriel Aguilar Pérez",
            "email": "203452@ids.upchiapas.edu.mx", "matricula": "203452"},
        {"name": "Hiram Méndez", "email": "213456@ids.upchiapas.edu.mx",
            "matricula": "213456"},
        {"name": "Isaura Valeria Plata Rojas",
            "email": "221216@ids.upchiapas.edu.mx", "matricula": "221216"},
        {"name": "Jesús Alejandro Guillen Luna",
            "email": "221198@ids.upchiapas.edu.mx", "matricula": "221198"},
        {"name": "Jesús David Ruiz Garcia",
            "email": "221263@ids.upchiapas.edu.mx", "matricula": "221263"},
        {"name": "Jesus Ignacio Velazquez Hernandez",
            "email": "221225@ids.upchiapas.edu.mx", "matricula": "221225"},
        {"name": "Joel De Jesús López Ruíz",
            "email": "221204@ids.upchiapas.edu.mx", "matricula": "221204"},
        {"name": "Jonathan Jair Pérez Mejía",
            "email": "221215@ids.upchiapas.edu.mx", "matricula": "221215"},
        {"name": "Jorge Alexis Arredondo Juárez",
            "email": "221187@ids.upchiapas.edu.mx", "matricula": "221187"},
        {"name": "Jorge Arturo Molina Gomez",
            "email": "221251@ids.upchiapas.edu.mx", "matricula": "221251"},
        {"name": "Jorge Brandon Chandomi Esponda",
            "email": "213500@ids.upchiapas.edu.mx", "matricula": "213500"},
        {"name": "José Ángel Nataren Ordoñez",
            "email": "213367@ids.upchiapas.edu.mx", "matricula": "213367"},
        {"name": "Jose Angel Ortega Merlin",
            "email": "221255@ids.upchiapas.edu.mx", "matricula": "221255"},
        {"name": "José Fernando Duran Villatoro",
            "email": "221237@ids.upchiapas.edu.mx", "matricula": "221237"},
        {"name": "Lorenzo Ramón Pérez Morales",
            "email": "203427@ids.upchiapas.edu.mx", "matricula": "203427"},
        {"name": "Luis Adrian Pozo Gomez",
            "email": "221218@ids.upchiapas.edu.mx", "matricula": "221218"},
        {"name": "Luis Alejandro Martinez Montoya",
            "email": "213021@ids.upchiapas.edu.mx", "matricula": "213021"},
        {"name": "Luis Antonio Ramirez Nucamendi",
            "email": "221260@ids.upchiapas.edu.mx", "matricula": "221260"},
        {"name": "Luis Humberto Escobar Gutierrez",
            "email": "211134@ids.upchiapas.edu.mx", "matricula": "211134"},
        {"name": "Luis Osvaldo Pérez Ángel",
            "email": "221258@ids.upchiapas.edu.mx", "matricula": "221258"},
        {"name": "Manuel Alejandro Peregrino Clemente",
            "email": "221324@ids.upchiapas.edu.mx", "matricula": "221324"},
        {"name": "Marco Darinel Ortiz Diaz",
            "email": "221213@ids.upchiapas.edu.mx", "matricula": "221213"},
        {"name": "Marcos Alejandro Shilon Gallegos",
            "email": "203459@ids.upchiapas.edu.mx", "matricula": "203459"},
        {"name": "María José Domínguez Costa",
            "email": "213457@ids.upchiapas.edu.mx", "matricula": "213457"},
        {"name": "Mario Ernesto Viloria Bonifaz",
            "email": "211110@ids.upchiapas.edu.mx", "matricula": "211110"},
        {"name": "Martin De Jesús Ochoa Espinosa",
            "email": "221254@ids.upchiapas.edu.mx", "matricula": "221254"},
        {"name": "Nancy Guadalupe Jimenez Escobar",
            "email": "221201@ids.upchiapas.edu.mx", "matricula": "221201"},
        {"name": "Noé Alejandro Rodríguez Moto",
            "email": "221219@ids.upchiapas.edu.mx", "matricula": "221219"},
        {"name": "Omar Ceja Sanchez",
            "email": "203460@ids.upchiapas.edu.mx", "matricula": "203460"},
        {"name": "Pedro Josafat Ruiz Robles",
            "email": "213537@ids.upchiapas.edu.mx", "matricula": "213537"},
        {"name": "Pedro Portillo Rodriguez",
            "email": "221217@ids.upchiapas.edu.mx", "matricula": "221217"},
        {"name": "Rodrigo Morales León",
            "email": "203457@ids.upchiapas.edu.mx", "matricula": "203457"},
        {"name": "Rogelio Emanuel Roque Morales",
            "email": "213532@ids.upchiapas.edu.mx", "matricula": "213532"},
        {"name": "Samuel Alberto Escobar Hernández",
            "email": "221238@ids.upchiapas.edu.mx", "matricula": "221238"},
        {"name": "Ulises Gálvez Miranda",
            "email": "213691@ids.upchiapas.edu.mx", "matricula": "213691"},
        {"name": "Veronica Velasco Jimenez",
            "email": "221224@ids.upchiapas.edu.mx", "matricula": "221224"},
        {"name": "Yahir Alberto Albores Madrigal",
            "email": "221228@ids.upchiapas.edu.mx", "matricula": "221228"},
        {"name": "Yahir Alexander Gutiérrez Martínez",
            "email": "221200@ids.upchiapas.edu.mx", "matricula": "221200"},
        {"name": "Yoshtin German Gutierrez Perez",
            "email": "221246@ids.upchiapas.edu.mx", "matricula": "221246"},
        {"name": "Yumari Teresa Morales Mendoza",
            "email": "211225@ids.upchiapas.edu.mx", "matricula": "211225"}
    

]

# Agregar los campos adicionales con números aleatorios para cada registro
for person in data_full:
    if isinstance(person, dict):  # Asegurarse que 'person' sea un diccionario
        person.update({
            "Grado": "8B",
            "C1": random.randint(10, 100),
            "C2": random.randint(10, 100),
            "C3": random.randint(10, 100)
        })
    else:
        print("Error: Un elemento en 'data_full' no es un diccionario")

# Especificar la ruta del archivo JSON donde se guardarán los datos
json_file_path = "Contactos_Completos_UPChiapas.json"

# Crear y guardar el archivo JSON con todos los datos
with open(json_file_path, "w", encoding='utf-8') as file:
    json.dump(data_full, file, ensure_ascii=False, indent=4)

print(f"Archivo JSON creado con éxito: {json_file_path}")
